name: CI Pipeline

#Triggers the workflow on push and pull reques, only for "main" branch
on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
  #Allows you to manually trigger a workflow run 
  workflow_dispatch:

jobs:
  test:
    #Integrate HTML validation into your CI/CD pipeline. You can use tools like HTMLHint (which is available as an NPM package) to 
    #automate checking your HTML for syntax errors and best practices.
    html-lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install HTMLHint
        run: npm install htmlhint
      - name: Run HTMLHint
        run:  npx htmlhint 'path/to/your/html/files/**/*.html'
        #The npx command is used to run binaries from the node_modules/.bin directory, making sure that the locally installed 
        #versions of htmlhint and stylelint are executed.

    
       



    
