name: CI Pipeline

#Triggers the workflow on push and pull reques, only for "main" branch
on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
  #Allows you to manually trigger a workflow run 
  workflow_dispatch:

jobs:
  test:
  
    #Integrate HTML validation into your CI/CD pipeline. You can use tools like HTMLHint (which is available as an NPM package) to 
    #automate checking your HTML for syntax errors and best practices.
    html-lint:
      runs-on: ubuntu-latest
      steps:
      #Check out the repository
      - uses: actions/checkout@v2

      #Install HTMLHint to validate HTML files
      - name: Install HTMLHint
        run: npm install htmlhint
      
      #Run HTMLHint to lint HTML files
      - name: Run HTMLHint
        run:  npx htmlhint 'AbbyPhotography/**/*.html'
        #The npx command is used to run binaries from the node_modules/.bin directory, making sure that the locally installed 
        #versions of htmlhint and stylelint are executed.

    css-lint:
      runs-on: ubuntu-latest
      steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Stylelint to lint CSS files
      - name: Install Stylelint
        run: npm install stylelint

      # Run Stylelint to lint CSS files
      - name: Run Stylelint
        run: npx stylelint 'AbbyPhotography/**/*.css'
      
    javascript-selenium:
      runs-on: ubuntu-latest
      services:
        selenium:
          image: selenium/standalone-chrome
          ports:
            - 4444:4444
      steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies required for Selenium tests
      - name: Install Dependencies
        run: npm install selenium-webdriver jest

      # Run Selenium tests using Jest
      - name: Run Selenium Tests
        run: npx jest 'AbbyPhotography/workflows/**/*.test.js'



    
