name: CI CD Pipeline

#Triggers the workflow on push and pull reques, only for "main" branch
on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
  #Allows you to manually trigger a workflow run 
  workflow_dispatch:

 
jobs:
  test:
     #Integrate HTML validation into your CI/CD pipeline. You can use tools like HTMLHint (which is available as an NPM package) to automate checking your HTML for syntax errors and best practices.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install HTMLHint
        run: npm install htmlhint

      # Changed name to make it unique
      - name: Run HTMLHint
        run: npx htmlhint './AbbyPhotography/**/*.html' --config ./AbbyPhotography/.htmlhintrc
        #The npx command is used to run binaries from the node_modules/.bin directory, making sure that the locally installed versions of htmlhint and stylelint are executed.


  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures that this job only runs if the 'test' job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub Actions
          publish_dir: ./AbbyPhotography
